### ISSUE TITLE
Rejected subscribers should not be able to rematch

### ISSUE THREAD

**Issue by ariannam** [tanzquotient/tq_website#155] opened 2018-01-12 13:44 UTC
when selecting all subscribers and matching all the ones without partner, rejected single subscriber match automatically with new subscriber, resulting in an uneven number of subscriber and a subscriber with an already rejected partner. 
To do: unable rejected subscriber for matching

**Comment by renatobellotti** [comment] 2018-04-02 13:22
Duplicate of #125.

**Closed by renatobellotti** 2018-04-02 13:22 UTC
