### ISSUE TITLE
Partner email not recognized during course registration

### ISSUE THREAD

**Issue by thgoebel** [tanzquotient/tq_website#201] opened 2018-09-20 08:16 UTC
In the webform used to register for courses, the `partner email` field does not work for me (and my partner).
However, it does work the other work around, i.e. I can signup from my account, putting in my partner's.

**Steps to reproduce:**

_Make sure you are really using the right email_
1. Go to https://tanzquotient.org/en/accounts/email/, copy your primary email, and paste it into the _New Email_ field. Observe the `This e-mail address is already associated with this account.` message.
2. Send your email to your partner (still copy&pasting).

_Observe failure_

3. Have your partner signup for any course, and ask him/her to paste your email into the `partner email` field.
4. Observe error message ```There is no user for the email address you entered for your partner!```

**Comment by renatobellotti** [comment] 2018-09-20 10:40
Thanks for contacting us! :)

I could not reproduce the error. Are you sure you've used the email addresses that is also associated with your TQ accounts?
Also, please tell me the email addresses and the course you wish to enroll in so I can try to reproduce your special case. (no email addresses on Github; please send an email to informatik [aat] tq.vsethz.ch)

**Comment by renatobellotti** [comment] 2018-09-23 10:06
I was able to enrol in a test course with your partner. Please try to do so as well.

**Comment by renatobellotti** [comment] 2018-09-25 14:11
I've seen that you were able to successfully enrol in the course. I guess there was a typo when you tried to enrol in the courses?
Please let us know if you experience this issue again. If I don't hear anything from you until Friday, I will close this issue.

**Comment by renatobellotti** [comment] 2018-09-29 07:52
Could not be reproduced.

**Closed** 2019-04-09 18:47 UTC
