### ISSUE TITLE
Make it possible to completely delete a user account

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#108] opened 2017-10-04 14:28 UTC
Currently, there is the following error message:
```
IntegrityError/de/admin/auth/user/{var}/delete/
error(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`tq_website`.`userena_userenasignup`, CONSTRAINT `userena_userenasignup_user_id_1c892c31ae3a7cd1_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')
```

**Comment by renatobellotti** [comment] 2018-04-02 12:32
Possible solution:
- Create archive versions of the Subscribe, Payment etc. models that contain all necessary information as strings.
- Convert old (e. g. older than 1 year) subscribes, payments etc. to archived versions, then delete the hyperlinked ones.
- This also takes care of multiaccounts (#170 )

**Comment by DanielSparber** [comment] 2020-04-05 16:02
Duplicate of #209

**Closed by DanielSparber** 2020-04-05 16:02 UTC
Labels: bug, infrastructure
