### ISSUE TITLE
Integrated Newsletter/Email System

### ISSUE THREAD

**Issue by gitsimon** [tanzquotient/tq_website#65] opened 2017-03-14 21:22 UTC
We would like to integrate the newsletter system into TQ-System (currently it is realized as a separate system with manual transfer of newsletter subscribers/non-subscribers).
First attempt has shown that most Django newsletter plugins do not fit the goal, so we might have to implement an own solution as **a separate Django app** and integrate it with the User model (and maybe also use the [Django Post Office plugin](https://github.com/ui/django-post_office) for the mail templates).
Requirements:

- [ ] Define a model for groups of user or reuse Django groups, but groups should also be described semantically by TQ specific criteria, such as 'all teachers', 'all confirmed subscribers of course X', 'all users with the helper flag set' etc. However, it is fine if this semantic group possibilities are created programmatically, best in a dedicated file within the other apps. 
- [ ] Create a nice front-end view, maybe with a draft mode
- [ ] Ensure the mails are not stored only as Post Office Email instances, but also somewhere in a nicer format where the original chosen receiver groups are still obvious (and not only the individual recipients resolved from the group list)

**Comment by DanielSparber** [comment] 2020-04-14 12:42
Duplicate of #262

**Closed** 2020-04-14 12:42 UTC
Labels: new feature
